CREATE TABLE DEPLOYMENT (
	DEPLOYMENT_ID NUMBER(10,0),
	APPLICATION_NAME VARCHAR2(255),
	BAR_CHECKSUM VARCHAR2(255),
	BAR_RELEASE_ID VARCHAR2(255),
	BAR_FILE_NAME VARCHAR2(255),
	CREATED_BY_PROCESS VARCHAR2(255),
	CREATED_TIME TIMESTAMP,
	DEPLOYED_BY_USER_ID VARCHAR2(255),
	DEPLOYED_BY_USERNAME VARCHAR2(255),
	DEPLOYMENT_TIME TIMESTAMP,
	ENVIRONMENT VARCHAR2(255),
	INSTANCE_NAME VARCHAR2(255),
	INTEGRATION_SERVER VARCHAR2(255),
	UPDATED_TIME TIMESTAMP,
	PRIMARY KEY (DEPLOYMENT_ID)
)